### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Triggered0** [kito323/FMV-autoclickers#1]
FMV-autoclickers-main/FMV_merge_autoclick.py
[Win32Window(hWnd=656332)]
['🔇 Farming 4 | Farm Merge Valley - Discord']
['A11', 'A12', 'A13', 'A21', 'A22', 'A23', 'A31', 'A32', 'A33', 'A41', 'A42', 'A43', 'A51', 'A52', 'A53', 'A61', 'A62', 'A63', 'B11', 'B12', 'B13', 'B21', 'B22', 'B23', 'B31', 'B32', 'B33', 'B41', 'B42', 'B43']    
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "c:\Users\DELL\Desktop\FMV-autoclickers-main\FMV_merge_autoclick.py", line 179, in run
    anchor1 = np.array(pyautogui.locateCenterOnScreen("merge/Anchor_-3_12.png", confidence=0.9))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return wrappedFunction(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyautogui\__init__.py", line 204, in locateCenterOnScreen
    return pyscreeze.locateCenterOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 447, in locateCenterOnScreen
    coords = locateOnScreen(image, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 405, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 383, in locate
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyscreeze\__init__.py", line 273, in _locateAll_pillow
    raise NotImplementedError('The confidence keyword argument is only available if OpenCV is installed.')
NotImplementedError: The confidence keyword argument is only available if OpenCV is installed.

**Comment by kito323** [comment]
The merging script (and also timeturning one) have some prerequisites that need to be in place and I should have added to those to the README but unfortunatelly my game linked to my discord has since crashed basically and I cannot really add the needed documentation anymore. If you are interested I can give you written pointers about them for merging script and you can try to follow them:

First, you need specific resolution (I think) and go to the lower most end of the game field.
Main idea is that you need to have 2 anchor pieces and 9 placeholder pieces in specific positions as the code can only perform the merge logic if the board is set up correctly. You can check what and where they are from the png images and their names.
The coordinate system that describes anchors' locations is basically X-Y coordinate system when you look at the game field (not the rotated (yaw) perspective, but when you look at the screen and think how x-and-y pixels are oriented) and (0;0) is the location of the bottom most square in the middle (nothing happens in Y minus side of the coordinates) and pixel-wise the x-units are roughly twice as long as on y-axis (because it's like looking at the board from an angle, i.e pitch). Every coordinate like that indicates the centers and corners of the square fields and is mid-step between the translation of pixel coordinates and the logical chess-board-style coordinates.
The placeholders are the single wood pieces (R11) and those need to be at the bottom and in a 3x3 formation if you think of the rotated (yaw and pitch) board (chessboard style).
Finally, before the start the board needs to be filled with items to be merged. Later it will refill it itself. Keep in mind that the code works on the given area that fits the screen (roughly) - 18x17 logical chessboard style (and some places removed like corners and where the railroad is).

AFAI remember, the code also prints out the logical table states every now and then so you can see if it classified items on the board correctly.
